name: neon
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core interpreter
  - python=3.9.18
  # PyTorch stack (CUDA 12.1 build)
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.1
  # CUDA libraries 
  - cudnn
  - nccl
  # Common scientific + IO
  - pip
  - numpy
  - scipy
  - pillow
  - psutil
  - click
  - requests
  - tqdm
  - imageio
  # Everything else via pip
  - pip:
      # Shared across repos
      - einops
      - matplotlib
      - seaborn
      - wandb
      - timm==1.0.8
      - imageio-ffmpeg
      - pyspng
      - omegaconf==2.3.0
      - hydra-core==1.3.2
      - typed-argument-parser
      - tensorboard==2.10.0
      - gdown==5.2.0
      - git+https://github.com/LTH14/torch-fidelity.git@master
      - diffusers==0.31.0
      - transformers
      - opencv-python-headless
      - accelerate
      - flash-attn --no-build-isolation