 
name: imagenet256_a2b4k12_mingap0.0001_fp16

logger:
  project: "imagenet"
  api_key: 55618b0a638ea3d0933cb1c317e27553dc85661f
  entity: sa86

outputdir: ./outputs
dataset:
  class_name: "training.dataset.ImageFolderDataset"
  path: imagenet_syn/ns30k.zip
  use_labels: true #this will dictate cond=true or false
  xflip: false
  cache: true

augment: null 

dataloader:
  pin_memory: true
  num_workers: 8
  prefetch_factor: 2

encoder:
  class_name: training.encoders.StabilityVAEEncoder
  vae_name: stabilityai/sd-vae-ft-ema
  final_std: 0.5
  raw_mean: [ 0.86488,    -0.27787343,  0.21616915,  0.3738409 ]
  raw_std: [4.85503674, 5.31922414, 3.93725398 , 3.9870003 ]  
  use_fp16: true 

network:
  class_name: training.preconds.IMMPrecond 
   
  model_type: "DiT_XL_2"  
  s_embed: true 
 
  noise_schedule: fm

  #sample function 
  f_type: euler_fm
  temb_type: stride 
  time_scale: 1000

  sigma_data: 0.5

  eps: 0.
  T: 0.994
 
  mixed_precision: fp16


loss:
  class_name: training.loss.IMMLoss
  #kernel 
  sigma: 1  
   
  sample_t_mode: uniform 
   
  matrix_size: 4

  sample_repeat: 1 
  

  a: 2
  b: 4
  k: 12
 
  label_dropout: 0.1
  min_tr_gap: 0.0001
 
  
optimizer:
  class_name: torch.optim.AdamW
  lr: 1e-6
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0.
  

training:
  total_ticks: 60
  ema_halflife_kimg: null
  ema_beta: 0.9999
 
  batch_size:  512
  batch_gpu: null
 
  cudnn_benchmark: true
  enable_tf32: false 
 
  kimg_per_tick:  102.4
  snapshot_ticks: 1
  state_dump_ticks: 1000
  ckpt_ticks: 50
  sample_ticks: 400
  eval_ticks: 5000
  
 
  #for eval 
  metrics: []

  seed: 0

  transfer: imagenet256_ts_a2.pkl
  

  # resume
  resume: null
  resume_tick: null
 

  num_samples: 16
  
 

sampling: 
  
  8_steps_cfg1.5_pushforward_uniform:
    name: pushforward_generator_fn 
    discretization: uniform
    num_steps: 8 
    cfg_scale: 1.5
     
  
eval:
  seed: 42
  cudnn_benchmark: true
  batch_size: 128
  batch_gpu: null 
  metrics: []
  resume: null
  detector_url: 'https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan3/versions/1/files/metrics/inception-2015-12-05.pkl'
  detector_kwargs: 
    return_features: True

  ref_stats: YOUR_PATH/dataset-refs/img256.pkl


hydra:  
  output_subdir: null  
  run:  
    dir: .
